import { landM2, parseNumber, parsePrice } from '../shared.js';
import { ProviderParsingError } from '../../core/errors.js';
const ARGONAUT = /window\.ArgonautExchange\s*=\s*(\{[\s\S]*?\})\s*;\s*(?:window\.|<\/script>|$)/;
export function extractArgonaut(html) { const match = html.match(ARGONAUT); if (!match) throw new ProviderParsingError('REA page contained no ArgonautExchange hydration data'); try { return JSON.parse(match[1]); } catch (error) { throw new ProviderParsingError(`REA hydration JSON was invalid: ${error.message}`); } }
function* payloads(exchange) { for (const app of Object.values(exchange ?? {})) { if (!app || typeof app !== 'object') continue; for (const raw of Object.values(app)) { if (typeof raw !== 'string') continue; try { const cache = JSON.parse(raw); for (const entry of Object.values(cache)) if (typeof entry?.data === 'string') try { yield JSON.parse(entry.data); } catch {} } catch {} } } }
const value = (x) => parseNumber(x?.value ?? x);
const image = (x) => x?.templatedUrl?.replace('{size}', '1024x768') ?? x?.url;
export function mapReaListing(raw) { const x = raw?.listing ?? raw; const a = x.address ?? {}; const f = x.generalFeatures ?? {}; const land = x.propertySizes?.land; const url = x._links?.canonical?.href ?? (x._links?.canonical?.path ? `https://www.realestate.com.au${x._links.canonical.path}` : undefined); const auctionText = [x.auction, x.auctionDetails, x.auctionDate, x.price?.display, x.price?.information, x.title, x.headline, x.description, x.badge?.label, x.status].filter(Boolean).join(' '); return { source: 'rea', sourceListingId: String(x.id ?? ''), sourceUrl: url, address: { fullAddress: a.display?.fullAddress ?? a.display?.shortAddress, street: a.display?.shortAddress, suburb: a.suburb, state: a.state, postcode: a.postcode }, coordinates: a.display?.geocode ? { latitude: Number(a.display.geocode.latitude), longitude: Number(a.display.geocode.longitude) } : undefined, price: parsePrice(x.price?.display ?? x.price?.information), propertyType: String(x.propertyType?.id ?? x.propertyType?.display ?? '').toLowerCase() || undefined, bedrooms: value(f.bedrooms), bathrooms: value(f.bathrooms), carspaces: value(f.parkingSpaces), landAreaM2: landM2(land?.displayValue, land?.sizeUnit?.displayValue), headline: x.title ?? x.headline, description: x.description, features: [...(x.features ?? []), ...(x.propertyFeatures ?? [])].map((v) => v?.display ?? v?.name ?? v).filter(Boolean), imageUrls: x.media?.images?.map(image).filter(Boolean), agent: { name: x.listers?.[0]?.name, agency: x.listingCompany?.name }, listingStatus: x.badge?.label ?? x.status, auctionDate: x.auctionDate ?? x.auction?.date ?? x.auctionDetails?.date, isAuction: Boolean(x.auction || x.auctionDetails || x.auctionDate || /auction/i.test(auctionText)), isNewBuild: /new|project|development/i.test(`${x.__typename ?? ''} ${x.productDepth ?? ''}`), raw: x }; }
export function parseReaHtml(html) { const exchange = extractArgonaut(html); for (const payload of payloads(exchange)) { const search = Object.entries(payload).find(([key, node]) => /Search$/.test(key) && node?.results)?.[1] ?? Object.values(payload).find((node) => node?.results?.exact?.items); if (!search) continue; const exact = search.results?.exact?.items ?? []; const surrounding = search.results?.surrounding?.items ?? []; return { listings: [...exact.map(mapReaListing), ...surrounding.map((x) => ({ ...mapReaListing(x), isSurrounding: true }))], totalPages: search.results?.pagination?.maxPageNumberAvailable, totalResults: search.results?.totalResultsCount }; } throw new ProviderParsingError('REA hydration contained no search result payload'); }
