import { createHash } from 'node:crypto';
const suffixes = { street: 'st', st: 'st', road: 'rd', rd: 'rd', avenue: 'ave', ave: 'ave', drive: 'dr', dr: 'dr', court: 'ct', ct: 'ct', place: 'pl', pl: 'pl', highway: 'hwy', terrace: 'tce', parade: 'pde', crescent: 'cres' };
export function normalizeAddress(address = {}) { const source = [address.street, address.suburb, address.state, address.postcode].filter(Boolean).join(' ') || address.fullAddress || ''; return source.toLowerCase().replace(/\b(unit|apt|apartment)\s*([a-z0-9-]+)/g, 'u$2').replace(/[^a-z0-9]+/g, ' ').trim().split(/\s+/).map((x) => suffixes[x] ?? x).join(' '); }
const distanceMetres = (a, b) => { if (!a || !b) return Infinity; const lat = ((a.latitude + b.latitude) / 2) * Math.PI / 180; const x = (a.longitude - b.longitude) * Math.cos(lat); const y = a.latitude - b.latitude; return Math.sqrt(x * x + y * y) * 111320; };
function levenshtein(a, b) { const row = [...Array(b.length + 1).keys()]; for (let i = 1; i <= a.length; i++) { let prev = row[0]; row[0] = i; for (let j = 1; j <= b.length; j++) { const old = row[j]; row[j] = Math.min(row[j] + 1, row[j - 1] + 1, prev + (a[i - 1] === b[j - 1] ? 0 : 1)); prev = old; } } return row[b.length]; }
const fuzzyScore = (a, b) => (!a || !b ? 0 : 1 - levenshtein(a, b) / Math.max(a.length, b.length));
const makePropertyId = (key) => createHash('sha256').update(key).digest('hex').slice(0, 20);
export function deduplicate(listings, options = {}) { const coordinateRadiusM = options.coordinateRadiusM ?? 25; const fuzzyThreshold = options.fuzzyThreshold ?? 0.94; const properties = [];
  for (const listing of listings) { const key = normalizeAddress(listing.address); let confidence = 0; let method; let match = properties.find((p) => { if (key && p.addressKey === key) { confidence = 1; method = 'address'; return true; } return false; }); if (!match) match = properties.find((p) => { const metres = distanceMetres(p.coordinates, listing.coordinates); if (metres <= coordinateRadiusM) { confidence = 0.98; method = 'coordinates'; return true; } return false; }); if (!match && key) match = properties.find((p) => { const score = fuzzyScore(p.addressKey, key); if (score >= fuzzyThreshold) { confidence = score; method = 'fuzzy-address'; return true; } return false; });
    if (match) { match.listings.push(listing); match.deduplication.push({ source: listing.source, confidence, method }); continue; }
    const identity = key || `${listing.source}:${listing.sourceListingId || listing.sourceUrl}`; properties.push({ propertyId: makePropertyId(identity), addressKey: key, address: listing.address, coordinates: listing.coordinates, bedrooms: listing.bedrooms, bathrooms: listing.bathrooms, carspaces: listing.carspaces, landAreaM2: listing.landAreaM2, listings: [listing], deduplication: [{ source: listing.source, confidence: 1, method: 'seed' }] });
  } return properties;
}
